blank_issues_enabled: false
contact_links:
  - name: Security issues
    url: https://github.com/sotruehq/.github/blob/main/SECURITY.md
    about: Please do not report security vulnerabilities as public issues.
